In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import tensorflow as tf
import glob
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, plot_confusion_matrix

In [2]:
#Función que separa los parametros t,g,v del fileName
def separateParams(fileName):
    t = fileName.split("t")[1].split("g")[0]
    rest_of = fileName.split("t")[1].split("g")[1].split("v")
    g, v = rest_of
    return float(t), float(g)/10, float(v)

In [3]:
#Se definen los sets de training, test y validación
def train_val_test_split(X, y, train_size, val_size, test_size, random_state = 1):
    if train_size + val_size + test_size != 1.0:
        print("Incorrect sizes!")
        return None 
    X_tmp, X_test, y_tmp, y_test = train_test_split(X, y, test_size = test_size, random_state=random_state)
    X_train, X_val, y_train, y_val = train_test_split(X_tmp, y_tmp, test_size = val_size/(test_size + train_size), random_state=random_state)
    return X_train, X_val, X_test, y_train, y_val, y_test

In [4]:
files = glob.glob('../data-lineas-espectrales/filtered_wv_models_old/*')
file_qty = len(files)
print("Files qty: {}".format(file_qty))

Files qty: 3100


In [5]:
y = np.zeros((file_qty,3))
df = pd.read_csv(files[0], sep=" ", header=None)
n_points , n_columns = df.shape
print("points: {} | columns: {} ".format(n_points, n_columns))

points: 201 | columns: 2 


In [6]:
#Matriz que contiene las lineas espectrales
X = np.zeros((file_qty, n_points))
#Matriz que contiene los labels de cada linea espectral
y = np.zeros((file_qty, 3))

print(X.shape)
print(y.shape)

(3100, 201)
(3100, 3)


In [7]:
#extract files, se almacenan las lineas espectrales y labels en X e y respectivamente
for i, name in enumerate(files):
    file_name = name.split("/")[-1].split(".")[0].split("_")[1]
    df = pd.read_csv(name, sep=" ", header=None)
    t, g, v = separateParams(file_name)
    #Se almacena la línea espectral
    X[i, :] = df[1].values
    #Se almacena el label de la linea espectral
    y[i] = t, g, v

In [8]:
print(y[:4])

[[1.9e+04 4.5e+00 2.2e+02]
 [3.0e+04 4.5e+00 2.3e+02]
 [3.8e+04 4.5e+00 3.0e+02]
 [3.4e+04 3.5e+00 3.2e+02]]
